# Generated by Django 5.2.11 on 2026-02-15 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="地点名称/标题")),
                ("desc", models.TextField(verbose_name="需求描述")),
                ("location_name", models.CharField(max_length=255, verbose_name="地点名")),
                (
                    "location_address",
                    models.CharField(max_length=255, verbose_name="地址详情"),
                ),
                (
                    "detail_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="具体位置"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="纬度"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="经度"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="积分")),
                ("deadline", models.DateTimeField(verbose_name="截止时间")),
                (
                    "task_type",
                    models.CharField(default="日常", max_length=50, verbose_name="类型"),
                ),
                (
                    "language",
                    models.CharField(default="普通话", max_length=50, verbose_name="语言"),
                ),
                (
                    "video_specs",
                    models.CharField(default="1080P", max_length=50, verbose_name="规格"),
                ),
                ("guide_text", models.TextField(default="[]", verbose_name="拍摄指南JSON")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("ongoing", "进行中"),
                            ("completed", "已完成"),
                            ("expired", "已过期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "result_video",
                    models.FileField(
                        blank=True, null=True, upload_to="videos/", verbose_name="交付视频"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接单者",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="流水标题")),
                ("amount", models.IntegerField(verbose_name="变动金额")),
                (
                    "trans_type",
                    models.CharField(
                        choices=[("income", "收入"), ("expense", "支出")],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(default="微信用户", max_length=50, verbose_name="昵称"),
                ),
                (
                    "uid_tag",
                    models.CharField(
                        default="0000", max_length=4, verbose_name="UID尾号"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="avatars/default.png",
                        upload_to="avatars/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, unique=True, verbose_name="手机号"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("男", "男"), ("女", "女"), ("未知", "未知")],
                        default="未知",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                ("balance", models.IntegerField(default=0, verbose_name="积分余额")),
                ("credit_score", models.IntegerField(default=100, verbose_name="信用分")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("nickname", "uid_tag")},
            },
        ),
    ]
