# Generated by Django 5.2.11 on 2026-02-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="balance",
            field=models.IntegerField(default=10000, verbose_name="积分余额"),
        ),
    ]
