# Generated by Django 5.2.11 on 2026-02-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_alter_userprofile_balance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "用户资料", "verbose_name_plural": "用户资料"},
        ),
        migrations.AddField(
            model_name="task",
            name="orientation",
            field=models.CharField(
                choices=[("portrait", "竖屏 (9:16)"), ("landscape", "横屏 (16:9)")],
                default="portrait",
                max_length=20,
                verbose_name="画幅",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="video_specs",
            field=models.CharField(default="1080P", max_length=50, verbose_name="画质规格"),
        ),
    ]
